DROP TABLE IF EXISTS tbl_a CASCADE;
CREATE TABLE tbl_a (
  id INTEGER PRIMARY KEY,
  g_n16 INTEGER
);

DROP TABLE IF EXISTS tbl_b CASCADE;
CREATE TABLE tbl_b (
  id INTEGER PRIMARY KEY,
  fk_n6 INTEGER,
  fk_n8 INTEGER,
  fk_n14 INTEGER,
  fk_n18 INTEGER,
  g_n10 INTEGER
);

DROP TABLE IF EXISTS tbl_c CASCADE;
CREATE TABLE tbl_c (
  id INTEGER PRIMARY KEY,
  fk_n12 INTEGER,
  fk_n15 INTEGER
);
