-- IMDB / JOB data. CSVs use backslash-escaped quotes, hence ESCAPE E'\\'.
TRUNCATE aka_name, aka_title, cast_info, char_name, comp_cast_type, company_name, company_type, complete_cast, info_type, keyword, kind_type, link_type, movie_companies, movie_info, movie_info_idx, movie_keyword, movie_link, name, person_info, role_type, title;
\copy aka_name FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/aka_name.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy aka_title FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/aka_title.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy cast_info FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/cast_info.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy char_name FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/char_name.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy comp_cast_type FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/comp_cast_type.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy company_name FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/company_name.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy company_type FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/company_type.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy complete_cast FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/complete_cast.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy info_type FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/info_type.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy keyword FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/keyword.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy kind_type FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/kind_type.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy link_type FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/link_type.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy movie_companies FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/movie_companies.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy movie_info FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/movie_info.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy movie_info_idx FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/movie_info_idx.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy movie_keyword FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/movie_keyword.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy movie_link FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/movie_link.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy name FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/name.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy person_info FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/person_info.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy role_type FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/role_type.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
\copy title FROM '/home/kaler/Downloads/samproject/SAM/sam_multi/datasets/job/title.csv' WITH (FORMAT csv, HEADER true, ESCAPE E'\\')
ANALYZE;
